TITLE = "title"
CREATOR = "creator"
DATE = "date"
PUBLISHER = "publisher"
SOURCE = "source"
IDENTIFIER = "identifier"
TYPE = "type"
FORMAT = "format"
GENRE = "genre"
PERIOD = "period"
THEME = "theme"
GENDER = "gender"
PATH = "path"
URL = "url"

